server:
  port: 8100
  servlet:
    context-path: /hw7
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  thymeleaf:
    prefix: classpath:/WEB-INF/
    suffix: .html
    templateMode: HTML

